- disable ipic due to:   arch/powerpc/sysdev/built-in.o: In function `ipic_suspend':   ipic.c:(.text+0x4780): undefined reference to `fsl_deep_sleep'   [or enable PPC_83XX]
Changed files:
    kernel-vanilla-multiarch.conf -> 1.128